### ISSUE TITLE
Extbase configuration missing

### ISSUE THREAD

**Issue by liayn** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#1131]
Obviously some information got lost in the transition 
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/f006faeedc90a20db08489978d9d59790656c735
by
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1983

The extbase configs for `features.*` are missing in main-version now,
Moreover, the `view.defaultPid` option is present in current [v11](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.html#extbase_typoscript_configuration-view)
But not in the current reference
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/TopLevelObjects/Plugin.html#view
(https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2665) wasn't added to newer version?

**Comment by brotkrueml** [comment]
Regarding Extbase feature toggles:

They are listed in the TypoScript Reference for v12:
https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/TopLevelObjects/Module.html
https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/TopLevelObjects/Plugin.html#features

They have been deprecated in v12 and were removed in v13:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100622-ExtbaseFeatureToggles.html

**Comment by liayn** [comment]
> Regarding Extbase feature toggles:
> 
> They are listed in the TypoScript Reference for v12: https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/TopLevelObjects/Module.html https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/TopLevelObjects/Plugin.html#features
> 
> They have been deprecated in v12 and were removed in v13: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100622-ExtbaseFeatureToggles.html

Thanks, good point.

**Comment by linawolf** [comment]
I think this can be closed then.
