### ISSUE TITLE
includeJSLibs/includeJSFooterlibs not matching current behaviour

### ISSUE THREAD

**Issue by mavolkmer** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#1258]
### Current behavior
Currently TYPO3 core does not work as described in documentation of `page.includeJSLibs` / `page.includeJSFooterlibs`
There is some inconsistency in code which is already described in https://forge.typo3.org/issues/103882

|page.include...              	| data.data-xxx / data.foo 	| data-xxx / foo 	|
|--------------	|--------------------------	|----------------	|
| CSS          	| Exception                	| +              	|
| CSSLibs      	| Exception                	| +              	|
| JS           	| +                        	| -              	|
| JSFooter     	| +                        	| -              	|
| JSLibs       	| Exception                	| +              	|
| JSFooterlibs 	| Exception                	| +              	|

Array to String Exception, as a string is expected but an array gets delivered
+: working as expected
-: not working

Thus the documentation needs to be adjusted to show the current state of the code.

### TYPO3 versions

12

### Possible Solution

see PR #1259

**Comment by garvinhicking** [comment]
Closed via #1259 - Thanks a lot for directly addressing this with a PR! :)
