### ISSUE TITLE
Outdated information about typolink.userfunc

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#1275]
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Typolink.html#userfunc states:

> The userfunction must return an <A>-tag.

but in reality this will lead to an exception `calling typolink.userFunc resulted in not returning a valid typolink` as the return value must now be an instance of `LinkResultInterface`.

Simple example would be 

```php
return (new LinkResult(LinkService::TYPE_URL, 'https://typo3.org'))
            ->withLinkText('I am a link');
```

docs should also provide an example with TYPE_PAGE

**Comment by garvinhicking** [comment]
Changelog reference for this:  https://review.typo3.org/c/Packages/TYPO3.CMS/+/72999 |
