### ISSUE TITLE
subkeys for siteLanguage.locale

### ISSUE THREAD

**Issue by froemken** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#1409]
We should check, if siteLanguage.locale works correct in TYPO3 core

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/1396/files#r1825677908

**Comment by froemken** [comment]
It's not a Core bug. I expect `.` as divider for `subkey` here:
https://docs.typo3.org/m/typo3/reference-typoscript/13.4/en-us/Functions/Data.html#data-type-siteLanguage

Further you mentioned `locale.full` as one example where `.` is the divider.

But in core it's a colon `:`:
https://github.com/TYPO3/typo3/blob/v13.4.0/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L4071

I would prefer to update the example and add a note about the colon as divider.

**Comment by froemken** [comment]
PR: #1396

**Comment by linawolf** [comment]
PR was merged
