### ISSUE TITLE
Integrate german reference of new Conditions

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#202]
> @georgringer  [9:50 AM]
hey. just as information https://www.typo3lexikon.de/typo3-tutorials/typoscript/referenz/condition-syntax.html wouldn't it be asesome to port that to the officitial docs? just published by @froemken

**Comment by sypets** [comment]
Please note that the TypoScript syntax description has already been moved to "TYPO3 Explained" by Lolli: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/TypoScriptSyntax/Index.html

So, I think adding that there might be a good idea. 

This also contains a section about [Conditions](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/TypoScriptSyntax/Syntax/Conditions.html). There is also a section about Symfony expression language there, but that is very thin. 

Of course, the Changelog contains https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.4/Feature-85829-ImplementSymfonyExpressionLanguageForTypoScriptConditions.html

As often the case for new features, the Changelog already contains extensive information.

How to deal with this is a general question. Please see the issues that I opened:

* [Question: How to deal with Changelog becoming main documentation for some new features?](https://github.com/TYPO3-Documentation/T3DocTeam/issues/75)
* [Question: Should more links be added to Changelog? decision required](https://github.com/TYPO3-Documentation/T3DocTeam/issues/76)

**Comment by sypets** [comment]
Actually, a lot of the to be ported text is already in the Changelog. Though the to be ported text is a little clearer and nicer to read.

**Comment by DanielSiepmann** [comment]
I could not find any reference listing all possible conditions since release 9.5, except the changelog.

So I would include Stefans work back into TypoScript Reference as Condition Reference, as it was before: https://docs.typo3.org/typo3cms/TyposcriptReference/8.7/Conditions/Reference/Index.html

I guess we should have a full reference, within the reference. Core API just covers the Syntax, which is fine, because TypoScript is either the Frontend TypoScript, or the Syntax, which is also usable within TSconfig for Pages and Users. And can also be used by developers using the parser.
