### ISSUE TITLE
Add module. ?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#203]
With TypoScript, you can also configure modules. Could be added to [Setup](https://docs.typo3.org/typo3cms/TyposcriptReference/latest/Setup/Index.html) menu, just like [plugin](https://docs.typo3.org/typo3cms/TyposcriptReference/latest/Setup/Plugin/Index.html).

**Comment by linawolf** [comment]
This has been idle
