### ISSUE TITLE
What context?

### ISSUE THREAD

**Issue by fabtho** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#206]
I try to use **backend.user.isLoggedIn** in my typo setup, its not working. What is meant by "The values are context related." on this page?

https://docs.typo3.org/typo3cms/TyposcriptReference/Conditions/Reference.html#variables

this works:

```
[getTSFE().isBackendUserLoggedIn() == true] 

[end]
```

this not:

```
 [backend.user.isLoggedIn == true]
 
 [end]
```

I even had a look at TYPO3 source, no luck.

context?  

* https://blog.marit.ag/2014/11/03/typo3-context-verstehen-und-anwenden/
* https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Context/

**Comment by fabtho** [comment]
another version, untested:

```
// Ab TYPO3 9.4:
[getTSFE().beUserLogin]

[end]
```

source: https://wiki.sebkln.de/doku.php?id=typo3:about:conditions

**Comment by linawolf** [comment]
This has been idle, condition syntax has changed since then
