### ISSUE TITLE
Can we merge "Objects and properties" chapter with other chapters?

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#224]
It's quite hard to me to find what I'm looking for by looking at the chapters of the Typoscript Reference.
Where should I look fro PAGE object documentation?
In "Objects and properties"?  
(https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ObjectsAndProperties/Index.html)

In Content objects?
 (https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Index.html)

In data types? 
(https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/DataTypes/Index.html#tag)

Nop, its in "Setup" » "PAGE"

I think  "Objects and properties" should be merged with other chapters

**Comment by erredeco** [comment]
I agree with putting Top level Objects like "PAGE" inside "Objects and properties"; Not quite sure about the "config"... can it be classificated as "Top Level Object"?

**Comment by tmotyl** [comment]
I would merge "Objects and properties" into "functions"

**Comment by sypets** [comment]
These are the notes I took when we talked about the structure of the TypoScript reference during t3init:

general:

* short pages with very little content you have to click through

specific

* Introduction: Contains very little information about TypoScript. A real introduction and the separation of "about" content (e.g. credits, how to contribute) and introduction to the topic would be helpful
* there are **datatypes** and **datatype modifiers** (e.g. calc, e.g. useOptionSplitReplace). Move all datatypes and modifiers into datatypes
* merge `Objects & properties > Objects & stdWrap` with `Functions > stdWrap`
* move `setup > Top level objects` to `Top level objects`
