### ISSUE TITLE
FLUIDTEMPLATE properties table are rendered differently than tables for other cobjects

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#226]
file: Documentation/ContentObjects/Fluidtemplate/Index.rst
![image](https://user-images.githubusercontent.com/515397/64801769-7dd72b80-d589-11e9-847b-7336d8d2ea29.png)

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html

vs

![image](https://user-images.githubusercontent.com/515397/64801840-9d6e5400-d589-11e9-9b66-66fb2b83ea84.png)
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Case/Index.html

**Comment by sypets** [comment]
There was a discussion about what formatting to use: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/issues/57

AFAIK it is not finally decided. Also, Martin is currently working on another solution.

**Comment by linawolf** [comment]
This will be part of a larger overhaul of the whole reference
