### ISSUE TITLE
Make „cobj” „cobject” „content object” less confusing

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#229]
In typoscript reference, we are using names/wording which is sound the same for the newcommers thus makes it confusing.
See:
cObject  (as data type)
“cObjects” are also called “Content Objects”. See the section “Content Objects”.
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/DataTypes/Index.html#cobject

getText->cObj (a key)
"For CONTENT and RECORDS cObjects that are returned by a select query, this returns the row number (1,2,3,…) of the current cObject record."
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/DataTypes/Index.html#cobj

stdWrap->cObject (a key)
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Stdwrap.html#cobject

I don't know how to solve it yet, maybe it requires just some rewording, but maybe also changes to the core should follow.
Just wanted to state my experience with training new developers.

**Comment by sypets** [comment]
I addressed this along with my latest changes. But I think this still needs some work. I will reopen.

What I already did:

* Added glossary which clearly states what terms mean: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Glossary.html
* Changed phrasing in several places.

**Comment by sypets** [comment]
Some changes were made addressing this. If there are still problems, please reopen or create new issue.
