### ISSUE TITLE
Content objects are missing cache property

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#237]
since https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.4/Feature-64200-AllowIndividualContentCaching.html

Every content object supports `cache` property.

**Comment by DanielSiepmann** [comment]
This is not yet included into all cObjects, due to different markup usage. See #239 for further information.

**Comment by linawolf** [comment]
@DanielSiepmann @tmotyl can one of you make a PR about that?

**Comment by tmotyl** [comment]
@linawolf sorry, in the next 2months I would not be able to dig into that, I'm totally green in rst markup stuff and what is considered best practice in docs (why some pages are done in one way and others are different)

**Comment by DavidBruchmann** [comment]
@tmotyl don't mind about rst syntax, if you could add the important info just in text format that would be absolutely fine, the documentation team will care about the formatting.

**Comment by tmotyl** [comment]
@DavidBruchmann its already documented in some cobjects , see change: 
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/239/files
This ticket is about adding the same information to other objects too.

**Comment by DavidBruchmann** [comment]
@tmotyl thanks for the clarification, that makes it easier to work on it.
