### ISSUE TITLE
Check chapter 'optionsplit'

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#247]
https://typo3.slack.com/archives/C028JEPJL/p1572763150001400

![image](https://user-images.githubusercontent.com/307057/68134130-f28f6c00-ff21-11e9-812a-aa03e5346310.png)

![image](https://user-images.githubusercontent.com/307057/68134155-fde29780-ff21-11e9-81cf-1d4bd5ac73a5.png)

**Comment by linawolf** [comment]
@marble are you still planning to work on this? If so please reopen the issue
