### ISSUE TITLE
Find better explanation for FLUIDTEMPLATE

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#258]
> FLUIDTEMPLATE
The TypoScript object FLUIDTEMPLATE works in a similar way to the regular “marker”-based TEMPLATE object. However, it does not use markers or subparts, but allows Fluid-style variables with curly braces.

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html

This is not helpful for beginners to TYPO3. 

- What is it?
- What can you do with it?

While most of this may be self-explanatory from seeing the example, one or 2 sentences in the beginning would be useful. Or even more, if it serves the purpose.

## Resources:

* Wiki: https://wiki.typo3.org/FLUIDTEMPLATE_Content_Object (this is outdated but could be used as inspiration)

**Comment by DanielSiepmann** [comment]
I would also go for removal of mentioning marker. This is from times when everyone was used to marker and FLUIDTEMPLATE got introduced.

We should instead focus on beginner and explain it, like you mentioned, in a way that's understandable.

**Comment by sypets** [comment]
We could also link to existing documentation in "Sitepackage Tutorial" which covers this in more depth: https://docs.typo3.org/m/typo3/tutorial-sitepackage/master/en-us/TypoScriptConfiguration/Index.html
