### ISSUE TITLE
data type "array" missing?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#268]
In the 9.5 version there is a reference to :ref:`data-type-array` in Setup/Config/Index.rst

Both this label is missing and a description of the data type array. I would expect it to be in DataTypes/Index.rst.

**Setup/Config/Index.rst**

```
htmlTag.attributes
==================

.. container:: table-row

   Property
         htmlTag.attributes

   Data type
         :ref:`data-type-array`
```

**Comment by linawolf** [comment]
Issue has been stale for a year
