### ISSUE TITLE
Datatype "<A>-params" missing

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#269]
Used in **ATagParams**

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html#atagparams

Should be defined and linked to in https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/DataTypes/Index.html

**Comment by linawolf** [comment]
Has been stale for over a year
