### ISSUE TITLE
typolink chapter lists property "target" twice

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#275]
1. 

> Target used for external links

https://docs.typo3.org/m/typo3/reference-typoscript/draft/en-us/Functions/Typolink.html#target

2.

> Target used for internal links

https://docs.typo3.org/m/typo3/reference-typoscript/draft/en-us/Functions/Typolink.html#typolink-target

I assume, the first target should be **extTarget** because that is what is listed as "property"

**Comment by linawolf** [comment]
This is fixed already
