### ISSUE TITLE
typolink: why is there target and extTarget if you can already specify the page / external URL etc. with parameter?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#276]
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Functions/Typolink.html

Just wondering if I am missing something.

**Comment by franzholz** [comment]
There is written something in the documentation:

> Target or popup settings

> Targets are normally as described above (extTarget, fileTarget, target). But it is possible to override them by explicitly defining a target in the parameter property. It’s possible to use a dash (-) to skip this value when one wants to define a third or fourth value, but no target.

And a target might be set globally by a constant for many different links in setup. This can only be done if target is a special setup outside of parameters.

**Comment by linawolf** [comment]
@sypets can this issue be closed then? Seems like all information is in the docu or what are you missing?

**Comment by sypets** [comment]
ok, I'll close.
