### ISSUE TITLE
Stucture: some filenames were changed across versions - problem with version switching and backporting of changes

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#277]
e.g. 9.5 and above:

`Functions/Typolink.html`

8.7 and below:

`Functions/Typolink/Index.html`

## problems

While the change itself is good (it simplifies the file structure and reduces unnecessary subdirs), this causes problems:

* it is not possible to switch between versions easily. This is only possible if the file (and URL) is the same after `/version/en-us/`
* it is not possible to backport changes easily

## Solution

We should analyze the effort and see if we can backport some of the file changes, at least to 8.7.

**Comment by linawolf** [comment]
This has been idle since a year. We have to work on this either on the fly or find a more general solution
