### ISSUE TITLE
Limitations on select.orderBy in TypoScript

### ISSUE THREAD

**Issue by bmack** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#279]
hey team,

I just stumbled over this issue and I think we should document that the markers are discouraged to be used:

https://forge.typo3.org/issues/87799

All the best,
Benni.

**Comment by sypets** [comment]
Discouraged to be used or no longer supported?

Discouraged to be used since version x?

**Comment by bmack** [comment]
My proposal is (as described in a ticket):

1. It has technical limitations and can be built in a better way with stdWrap - so we can
- create an example on how to do this with the stdWrap logic
- put a note on this option "Hey, if you want to put logic in "orderBy", you should look for stdWrap properties

2. I put it on my list to deprecate it in TYPO3 v10, but we could adapt this for v9+v10 documentation already. For the deprecation + removal we will have an RST then once I finish it.

**Comment by linawolf** [comment]
@bmack What is the status on this? Has the option been deprecated in 10?

**Comment by bmack** [comment]
Nope. Not yet.

**Comment by linawolf** [comment]
There is already a warning in the TsRef about this. We will work on the deprecation note as it comes

**Comment by linawolf** [comment]
As soon as this is deprecated we will know by the changelogs. Closing this for now.
