### ISSUE TITLE
Defining constants: Extend examples

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#282]
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/UsingSetting/Constants.html

This is the example

```
bgCol = red
file {
    toplogo = fileadmin/logo.gif
}
topimg {
    width = 200
    file.pic2 = fileadmin/logo2.gif
}
```

Use an example with the typical comment line, e.g. ?

```
# cat=header; type=string; label=Background color;Background color used in header section (default: red)
bgCol = red

# cat=header; type=int; label=Width of top image
topImageWidth
```

**Comment by sypets** [comment]
Ok, sorry, misunderstanding. Multiline **values**. I will correct it above. But in any case, using the descriptive comment in the example might be helpful.

**Comment by linawolf** [comment]
Actually the information about the constant editor is here: 
https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/UsingSetting/TheConstantEditor.html

**Comment by linawolf** [comment]
I would suggest to close this as the information is there. Please reopen if you think otherwise.
