### ISSUE TITLE
Readd documentation of special.targets

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#289]
This is a followup of https://forge.typo3.org/issues/90481 (which will be closed in favor of this one)

> This is for special = rootline only.
> You can set:
> 
> special.targets {
>  1 = _blank
>  2 = _self
>  3 ...
> }
> 
> The index stands for the rootline element.
> These values are taken, if no target is defined in the page data.

I can find the description in https://docs.typo3.org/m/typo3/reference-typoscript/7.6/en-us/ContentObjects/Hmenu/Index.html but not in master anymore

Caution: I didn't check the core itself but didn't find a rst which would mention the removal

**Comment by linawolf** [comment]
I  had a look in the core. It is still there even in 11.0

I got accidentally removed in a PR removing frame support from 8.7 as it mentions frames.
