### ISSUE TITLE
Make documentation about useCacheHash clearer (and about cHash in general)

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#293]
see https://forge.typo3.org/issues/90783#change-419730

We should explain what the setting does better and reference the general cHash documentation (if it exists) or write one explaining:

- What is the cHash
- Which settings influence it (TYPO3_CONF_VARS, Routing, Caching)
- Usage in UriBuilder / Fluid
- --> in v10 a lot of the old stuff is deprecated / rewritten so maybe now is the time :)

**Comment by sypets** [comment]
I don't think the "general cHash documentation" exists, not on docs.typo3.org. But, shouldn't that rather  be in T3 Explained? Maybe change "Caching Framework" to general "Caching" chapter there and add Introduction.

**Comment by sypets** [comment]
About chash, there is some info:

* [Mysteries of chash](https://typo3.org/article/the-mysteries-of-chash) (2005, by Kasper)
* b13: [Caching part 2](https://b13.com/blog/caching-in-typo3-part-2-cache-variants-of-a-page-with-chash) (2020, by Benni)

**Comment by linawolf** [comment]
@susannemoog @sypets how shall we solve this issue? Or can it be closed?

**Comment by susannemoog** [comment]
I think I wrote that documentation at some point based on a few changes in the core. See https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/CachingFramework/Index.html#caching-variants-or-what-is-a-cache-hash & https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1043

**Comment by linawolf** [comment]
Ok so lets close this then
