### ISSUE TITLE
Restructure section of DataProcessor in FLUIDTEMPLATE

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#298]
**Issue:**
Whenever I want to search and e.g. set a link to one of the DataProcessor examples, it's only possible to link to the general DataProcessor section.

**Solution:**
Either set headers to be possible to link to each DataProcessor or create a complete new page where it's possible to get a better and linkable overview of each DataProcessor.

What do you think?

**Comment by sypets** [comment]
I already thought about creating a subpage. I think that would be easier to maintain longterm. I am currently changing some things on the page. I will do this directly after.
