### ISSUE TITLE
cObect TEMPLATE makes no sense while FILE is gone

### ISSUE THREAD

**Issue by esokoll2** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#309]
Due the fact that FILE has been removed in TYPO3 v10, it would be good to write a note at cObject TEMPLATE how to migrate [1] old projects with an own extension or the use of the extension modern_template_building [2]

[1] https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-85970-FileContentObject.html#migration
[2] https://extensions.typo3.org/extension/modern_template_building/

**Comment by sypets** [comment]
Can you make a suggestion as pull request?

See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html

**Comment by sypets** [comment]
Related: #314

**Comment by linawolf** [comment]
@esokoll2, I made a PR addressing this problem. Please have a look if that solves the question for you:

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/397
