### ISSUE TITLE
Search for "image" does not find image page

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#310]
When searching for "image" on https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/Index.html I do not get the "IMAGE" documentation page https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/ContentObjects/Image/Index.html

![2020-06-04](https://user-images.githubusercontent.com/59036/83751867-db575f00-a667-11ea-8682-3022dd3c2671.png)

**Comment by sypets** [comment]
Did you accidentally use "image1"?

I cannot reproduce this.

![image](https://user-images.githubusercontent.com/13206455/84111500-58e3ec00-aa27-11ea-8c59-eb7f7bb63cae.png)

**Comment by cweiske** [comment]
I still see this with Firefox 76 and Chromium 81.
