### ISSUE TITLE
cssInline sample with FILE, but FILE is deprecated and no longer supported

### ISSUE THREAD

**Issue by dirk2014** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#313]
I guess there is a small bug in the TYPO3 documentation at

- https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html?highlight=cssinline#cssinline-array

There is used a TypoScript snippet with the content object FILE. But FILE is deprecated since 9.5 and isn't supported in TYPO3 10.2. See:

- https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/File/Index.html

**Comment by sypets** [comment]
Thank you for your report. I created a pull request: #315

In the future, you can also make changes yourself, see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html
