### ISSUE TITLE
How to use template in FLUIDTEMPLATE since TYPO3 9

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#314]
This is a question:

Since TYPO3 9.5, the `FILE` content object is deprecated, see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-85970-FileContentObject.html

Now, documentation should get changed. `FILE` is still used in `FLUIDTEMPLATE` in [template](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html#template) property and [example](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html#example):

```
page = PAGE
page.10 = FLUIDTEMPLATE
page.10 {
   template = FILE
   template.file = EXT:site_default/Resources/Private/Templates/MyTemplate.html
```

For TEMPLATE it is also used:

```
page.10 = TEMPLATE
page.10 {
   template = FILE
   template.file = fileadmin/template.html
}
```

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Template/Index.html#template

Since FILE is deprecated (and removed), this should get changed, but how?

* does it make sense to still have the `template` property at all (and not use the `file` property  instead)?
* how should the above code snippets look?

Related: #313

**Comment by sypets** [comment]
In fact, in TYPO3 10.4.4, using .file will work:

```
page = PAGE
page.1 = FLUIDTEMPLATE
page.1.file = fileadmin/templates/Fluidtemplate.html

```

But using .template in the documented way causes an exception:

```
page = PAGE
page.1 = FLUIDTEMPLATE
page.1.template = FILE
page.1.template.file = fileadmin/templates/Fluidtemplate.html

```

> Could not find template source for FILE

https://wiki.typo3.org/Exception/CMS/1437420865

**Comment by sypets** [comment]
In TYPO3 11 TEMPLATE will be removed. So we don't have to worry about that then.

For FLUIDTEMPLATE, using .template is not really necessary, since you can use .file instead. Should we just remove it?

**Comment by linawolf** [comment]
Merged
