### ISSUE TITLE
Add links to subheaders, give overview of properties on top of page (table of content on page)?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#323]
On some pages, we have (minimal) table of contents on the top:

Example: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Records/Index.html

1. Here, there is a small toc with depth 1 on top:

![image](https://user-images.githubusercontent.com/13206455/89020745-b4dc3a00-d31f-11ea-89b5-b61ab63b3205.png)

2. Also there is an overview of all properties:

![image](https://user-images.githubusercontent.com/13206455/89020782-c45b8300-d31f-11ea-8ff5-fd955d068c86.png)

It seems to me, we used to have this more and it got removed at one point. While making it is a bit more work, I think there the benefits outweigh the costs.

Advantages:

* You get a better overview what is on the page
* You can jump directly to the section

Disadvantages:

* For no 2 - the list of properties: This must be maintained manually which is annoying and you have to make changes twice. 

## Related

This was already done in TCA reference, for example:

* check (default) properties: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/checkDefault.html#properties

**Comment by sypets** [comment]
Done for FLUIDTEMPLATE (master, 10.4, 9.5): https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Fluidtemplate/Index.html

**Comment by linawolf** [comment]
Are you still working on this @syspets? If so please reopen the ticket
