### ISSUE TITLE
Add link to T3 Explained : Condition syntax on Condition page (8.7)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#332]
> For full explanations about conditions, especially about condition syntax, please refer to the according chapter in “TYPO3 Explained”.

on

* https://docs.typo3.org/m/typo3/reference-typoscript/8.7/en-us/Conditions/Syntax/Index.html
* and https://docs.typo3.org/m/typo3/reference-typoscript/8.7/en-us/Conditions/Index.html

does not contain a link

**Comment by linawolf** [comment]
8.7 is outdated.
