### ISSUE TITLE
Feature: 88648 - Set Twitter Card Type in page properties (10.0)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#343]
| Name        | Value     |
| -------------- | ----------- |
| Type:         |  Feature |
| Merged in: | 10.0       |
| Forge:         | [88648](https://forge.typo3.org/issues/88648) |
| Gerrit:        | [61163](https://review.typo3.org/c/Packages/TYPO3.CMS/+/61163) |
| Changelog: | [Set Twitter Card Type in page properties](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88648-DefineTwitterCardTypeInPageProperties.html) |
| Docs page: | [page.meta](https://docs.typo3.org/m/typo3/reference-typoscript/10.4/en-us/Setup/Page/Index.html#meta) |

Related:

* Forge issue: https://forge.typo3.org/issues/91939

**Comment by linawolf** [comment]
Merged
