### ISSUE TITLE
Feature: 86759 - Support nomodule attribute for JavaScript includes (10.2)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#344]
| Name        | Value     |
| -------------- | ----------- |
| Type:         |  Feature |
| Merged in: | 10.2       |
| Forge:         | [86759](https://forge.typo3.org/issues/86759) |
| Gerrit:        | [58908](https://review.typo3.org/c/Packages/TYPO3.CMS/+/58908) |
| Changelog: | [Support nomodule attribute for JavaScript includes](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.2/Feature-86759-SupportNomoduleAttributeForJavaScriptIncludes.html) |
| Docs page: | [page.includeJSFooter](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html#includejsfooter-array) |

**Comment by linawolf** [comment]
Merged
