### ISSUE TITLE
How to handle updates: should all changes since 7.6 have a note?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#347]
This is currently on the start page

> For new features TypoScript Reference includes a note in which TYPO3 version the feature was added. If such a note is missing, the feature is part of TYPO3 since version 7.6 at least.

While the note may have been added for some changes, it definitely was not added for all and unfortunately we are still not very consistent whether we add a note (or a .. versionchanged etc.) at all. 

In any case, we probably do not want to got back and add a note now for all that was changed, so I propose changing this text. 

Maybe for some important changes, we want to add the note.

**Comment by sypets** [comment]
The current "best practice" is to use the following directives:

```
.. deprecated:: 10.2
   The hook shown here is deprecated since TYPO3 10.2 - use a custom
   :ref:`PSR-15 middleware<request-handling>` instead.

.. versionadded:: 10.2
   Starting with TYPO3 10.2 hooks and signals have been replaced by a PSR-14 based
   event dispatching system.

.. versionchanged:: 2.3.1
   This feature was changed ...
```

https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Index.html

Using `.. deprecated::` also makes it easier to search for these for removal in the next versions.

**Comment by linawolf** [comment]
should we also remove the versionadded and versionchanged tags then or remove them also

**Comment by linawolf** [comment]
I would suggest we replace all version information with the directives in a first step. Then we can find all of them and decide how much version information we want to keep in future.

**Comment by linawolf** [comment]
Lets work on this on the fly. This isn't really a topic to be solved in a issue. It is a topic for all references
