### ISSUE TITLE
Wiki page: TypoScript Constants

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#351]
check if there is information on https://wiki.typo3.org/TypoScript_Constants which is missing from this reference.

Possible steps to take (depends on evaluation of information on Wiki page)

1. Use Wiki page to check if things missing in official docs and add the information
2. If Wiki page contains information for older TYPO3 versions that are not available on docs.typo3.org, the Wiki page can be kept, but a note and a link to newer documentation should get added, e.g.:

a) unmaintained
`{{unmaintained|https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Autoloading/Index.html}}`

which will get rendered as:

> Warning - No longer maintained
This document was transferred to the official TYPO3 CMS documentation (new URL: <url>). This wiki page is now obsolete and will not get any additional updates.

https://wiki.typo3.org/Autoload

b) has newer

`{{NewerVersion|Since TYPO3 10, the core uses [https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Hooks/EventDispatcher/Index.html PSR-14 Events], see also [https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Hooks/Events/Index.html List of Core PSR-14 Events]}}`

> Notice - Newer documentation available
Since TYPO3 10, the core uses PSR-14 Events, see also List of Core PSR-14 Events

https://wiki.typo3.org/Hook_programming

**Comment by linawolf** [comment]
The information is all contained in https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/UsingSetting/Constants.html

and https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/UsingSetting/TheConstantEditor.html

The wiki page can be removed / redirected

**Comment by linawolf** [comment]
@susannemoog can you delete and redirect the Wiki page and then close this issue?
