### ISSUE TITLE
Wrong code example for sys-language-isocode-default

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#40]
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#sys-language-isocode-default

![image](https://cloud.githubusercontent.com/assets/515397/9759772/de0dcb0c-56ef-11e5-9e96-64d990c89b80.png)

**Comment by marble** [comment]
Hi Tymoteusz, thanks for the bug report. I fixed it.

**Comment by tmotyl** [comment]
Thank you!
