### ISSUE TITLE
Elaborate on absRefPrefix

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#47]
https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#absrefprefix

Special value 'auto' deserves more explanation and maybe an example.

**Comment by Chrissitopher** [comment]
Maybe you want to integrate something from this?
https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.1/Feature-58366-AutomaticAbsRefPrefix.html

**Comment by r4fx** [comment]
why link above with Changelog/7.1/ stopped working?

**Comment by linawolf** [comment]
This issue has been idle since many years
