### ISSUE TITLE
Reference HMENU Object in Menu table of contents

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#58]
Right now the HMENU object is described here:
https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Hmenu/Index.html
However all other Menu objects are described here:
https://docs.typo3.org/typo3cms/TyposcriptReference/MenuObjects/Index.html

It's quite confusing.
I think we should at last add a HMENU entry in the MenuObjects table of contents so it's easier to find.

**Comment by Chrissitopher** [comment]
I agree that having this information at two different places is not very user-friendly. However, HMENU is a cObject, while the "Menu objects" are _only_ menu objects - and no cObjects. In so far the separation in fact is logical.

I'll add an according note to https://docs.typo3.org/typo3cms/TyposcriptReference/MenuObjects/Index.html

**Comment by Chrissitopher** [comment]
Done in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/4849b373a005376ea3a218e3940fcecc8b795b6c
