### ISSUE TITLE
wrong filelink.icon.path value for version 7.6 and above

### ISSUE THREAD

**Issue by erredeco** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#62]
pn https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Filelink/Index.html#icon

the information
`path: Path to the icon set. Default is typo3/gfx/fileicons/` is wrong for version 7.6.x and above; it should be `typo3/sysext/frontend/Resources/Public/Icons/FileIcons/`

**Comment by marble** [comment]
Hi Riccardo, great you spotted that and great you're in the league of contributor. To be become a full "documentation hero" learn about the method of contributing bei Github Pull Request. You will be routed to that track when you follow the "Edit me on Github" link at the right top of pages at docs.typo3.org. I've applied a change to branch 'latest' and branch '7-6'.
