### ISSUE TITLE
Property returnCount is duplicated

### ISSUE THREAD

**Issue by r4fx** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#65]
in Split function: 
https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Split/Index.html

**Comment by Chrissitopher** [comment]
Thanks for the note! I have just fixed the issue by updating the docs in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/7919f356099309cfde6387d0f33471ed140c7a70!
