### ISSUE TITLE
recordLinks does not exist in tsref. It is not documented there at all.

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#693]
recordLinks does not exist in tsref. It is not documented there at all.

_Originally posted by @brotkrueml in https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/324#discussion_r1051431327_

**Comment by DavidBruchmann** [comment]
@brotkrueml  What is about this:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/blob/main/Documentation/Setup/Config/Index.rst#recordlinks

**Comment by brotkrueml** [comment]
Seems fine. Needs an anchor an can then be linked.

**Comment by linawolf** [comment]
I think it can be closed then
