### ISSUE TITLE
Bad titles for optionSplit examples 

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#71]
The `optionSplit` examples only have "Example:" as title, which is not helpful in the TOC

https://docs.typo3.org/typo3cms/TyposcriptReference/7.6/ObjectsAndProperties/Index.html

![2016-08-08 typo3 optionsplit docs](https://cloud.githubusercontent.com/assets/59036/17475520/b4217bc2-5d5b-11e6-85d6-f394f35dfe55.png)

**Comment by marble** [comment]
Indeed. Please feel free to edit the sources at Github and send a PR (pull request). That would be awesome.

**Comment by Chrissitopher** [comment]
The menu currently shows more useful headlines after recent changes, e.g. https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/commit/ea811f084fc8b373d5993273520b7e5155b3b558.
