### ISSUE TITLE
"Add TypoScript in the backend" has some outdated content

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#804]
### Current behavior

The documentation about "Add TypoScript in the backend" has some outdated Screenshots and Designations. 

### Expected behavior/output

The Screenshots and Designations need to be updated for TYPO3 v12.

### Links

https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/UsingSetting/Entering.html

### TYPO3 versions

[12]

### Possible Solution

Take new Screenshots and keep the Designations up to date.

### Additional context

@wowaTYPO3 send me this problem, because it needs to be fixed

**Comment by brotkrueml** [comment]
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/136

**Comment by linawolf** [comment]
@FlorianT03 could you take new screenshots for us?

**Comment by FlorianT03** [comment]
Could add that to my To-Do's when I have time for it. But for the TYPO3 13 right? @linawolf

**Comment by linawolf** [comment]
Yeah 13 would even be better

**Comment by linawolf** [comment]
Done
