### ISSUE TITLE
Code examples of FILES don't work with non-default storages

### ISSUE THREAD

**Issue by smichaelsen** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#83]
The [code examples](https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Files/Index.html#usage-with-references) mention the following snippet twice to load the current file object in TypoScript:

    file.import.data = file:current:publicUrl

But that more or less only "accidentally" works and only for the default fileadmin storage.

The following snippet works across any storages:

    file.import.dataWrap = {file:current:storage}:{file:current:identifier}

**Comment by Chrissitopher** [comment]
Thanks for the note!
