### ISSUE TITLE
Search for "constants" does not find "constants" page

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#91]
When searching for `constants`, the `constants` page is not found.

Searching for `constant` (without s), the `constants` page is found.

![2017-01-06 docs typo3 org search constants](https://cloud.githubusercontent.com/assets/59036/21711591/ffc8efb4-d3ef-11e6-9750-f1a8469b3247.png)
![2017-01-06 docs typo3 org search constant](https://cloud.githubusercontent.com/assets/59036/21711596/04a73270-d3f0-11e6-85ee-c6a388f62b71.png)

**Comment by sypets** [comment]
Just noticed a problem if searching for FLUIDTEMPLATE. It will not have the FLUIDTEMPLATE page in the result set. As this problem may be related and probably could be best tackled in one batch, I am posting it here. 

![search-docs-fluidtemplate](https://user-images.githubusercontent.com/13206455/34774083-581fe2d0-f60e-11e7-99d7-59593549b7d5.png)

**Comment by marble** [comment]
Indeed, that should be working better. I'll refer to the problem here: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/issues/57

**Comment by lolli42** [comment]
The search engine will be later substituted with a better one. At the moment, we can't do much about it and first need a new rendering chain and server in place. I'll close this issue for the time being since it is a general issue on docs.typo3.org.
