### ISSUE TITLE
Docs > Functions > replacement

### ISSUE THREAD

**Issue by fresc81** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#92]
Can somone give me a hint on this? Especially the PCRE dialect for the _search_ property bugs me. Do I need to escape characters (it looks like especially [ ] characters classes don't seem to work as expected)? I can't get a simple Regex-replacement working (which works fine when using a PCRE evaluator/debugger instead). There's no detailed information about this feature, only 5 vague lines in the [TSDocs](https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Replacement/Index.html#replacement). Also the examples provided don't deal with character classes at all.

This is what I am trying to accomplish: I've got a text containing HTML markup and I want to extract the contents of some attributes without the (")-chars.

My Regular Expression looks like this: #"([^"]*)"#g
Replacement is \1 or \2 (the index of the found attribute)
Which somehow always evaluates to empty text.

Thanks in advance.

**Comment by marble** [comment]
Hello Paul @fresc81 actually you're aksing a question about how to solve a TYPO3 problem. The right place to ask that and to find the intended audience is to ask in the Slack channel https://typo3.slack.com/messages/typo3-cms/  Get your invitation and login from https://forger.typo3.org/slack This is the wrong place and only very few are reading here. Please ask again over there. There will be an answer !-))
