### ISSUE TITLE
Menu: "Condition reference" doubled in menu

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#99]
The left side menu shows "Conditon reference" twice:

- Conditions
  - Condition reference
    - Condition reference

https://docs.typo3.org/typo3cms/TyposcriptReference/Conditions/Index.html

![2017-05-30 t3doc ts condref](https://cloud.githubusercontent.com/assets/59036/26585468/77fd994e-454c-11e7-8864-1eb198a5aec3.png)

**Comment by marble** [comment]
I fixed this. Thanks for reporting. Keep on!
